language: node_js
node_js:
  - "7"
  - "stable"

install:
  - npm cache clean -f
  - npm install -g n
  - node --version
  - npm i

env:
  - NODE_ENV="test"

script:
  - npm run test
  - npm run lint

after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
