# language: node_js
# node_js:
#   - "stable"
#   - "iojs"
#   - "7"
# env:
#   - NODE_ENV="development"
# script:
#   - npm run test
#   - npm run lint

language: node_js
node_js:
  - "0.12"
  - "iojs"
  - "7"
  - "stable"

install:
  - npm cache clean -f
  - npm install -g n
  - node --version
  - npm i

script:
  - npm run test
  - npm run lint

after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
