# language: node_js
# node_js:
#   - "stable"
#   - "iojs"
#   - "7"
# env:
#   - NODE_ENV="development"
# script:
#   - npm run test
#   - npm run lint

language: node_js

install:
  - npm i

script:
  - npm run test
  - npm run lint

after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
