language: node_js
node_js:
  - "stable"
  - "iojs"
  - "7"
env: 
  - NODE_ENV="development"
  - NODE_ENV="production";SESSION_SECRET="la li"
script: bundle exec rake build && bundle exec rake builddoc