version: '2'

services:
  users-module:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: users-module
    ports:
      - "8010:8081"
      - "9615:9615"
    environment:
      - NODE_ENV=production
      - IP=127.0.0.1
      - PORT=8081
    networks:
      - users-network

networks:
  users-network:
    external: true
