version: '2'

services:
  users-module:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: users-module
    ports:
      - "8081:8081"
      - "9615:9615"
    environment:
      - NODE_ENV=production
      - IP=127.0.0.1
      - PORT=8081
      - ARANGODB_HOST="http://users-db:8529"
      - ARANGODB_USERNAME=root
      - ARANDODB_PASSWORD=mysecretpassword
      - APP_NAME="users-submodule-api"
    networks:
      - users-network
    depends_on:
      - users-db
      - redis
  users-db:
    image: arangodb/arangodb
    container_name: users-db
    volumes:
      - users-db-volume-data:/var/lib/arangodb3
      - users-db-volume-apps:/var/lib/arangodb3-apps
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=mysecretpassword
    networks:
      - users-network
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    container_name: redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - users-network

volumes:
  users-db-volume-data:
  users-db-volume-apps:
  redis-data:

networks:
  users-network:
    external: true
