version: '2'

services:
  users-module:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: users-module
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
      - IP=0.0.0.0
      - PORT=8081
